import Head from 'next/head'
import styles from '../styles/Dashboard.module.css'
import Dashboard from '../src/components/Dashboard'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Dashboard/>
     </div>
    </div>
  )
}
